### ISSUE TITLE
kernel size 5x5 and 3x3 results comparison not expected

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#5]
tested same in everything, except kernel size
**kernel_size = 3x3 (expected result)**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/d2ad29cb-3bc1-4ee9-a237-c168e1eaaa78)

**kernel_size = 5x5 (no error occured but not expected)**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/1cff950c-d44a-4f3f-942b-de3cda093e18)

tested another kernel like outline, dilation, emboss, laplacian, etc
the result is so different too

not every kernel can have size 5x5 and 3x3 
what do you think ?

just curious, where do you got the kernel size value for both 3x3 and 5x5
did you convert it manually ?

best regards

**Comment by amirho3einsedaghati** [comment]
Acutally, I get kernel_size by methods apply_filter_on_color_img and apply_filter_on_gray_img to create the builtin kernel names which are in the kernels dictionary when kernel_value is None.

honestly, I checked the issue you mentioned on a new image but got the expected and correct results. in the following images, you can see what I got.

![1](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/ddabd7a1-b352-4000-8d7a-7be822080149)

![2](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/d9991cc9-bcf4-4bbf-b4dc-93196f5d075b)

![res](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/01a4ff28-6a25-4e26-b190-b519dab2d9b2)

 I'm not sure why don't you get the same result. just make sure you are using the latest version published on [Pypi.org](https://pypi.org/project/pyimkernel/).
`pip install pyimkernel==1.2.0`

Best Regards @sugizo

**Comment by sugizo** [comment]
**execute**
`pip show pyimkernel`
**result**
```
Name: pyimkernel
Version: 1.2.0
Summary: Applying some image kernel(s) on a grayscale or RGB color-scale image
Home-page: https://github.com/amirho3einsedaghati/pyimkernel
Author: Amir Hosein Sedaghati
Author-email: [amirhosseinsedaghati42@gmail.com](mailto:amirhosseinsedaghati42@gmail.com)
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: matplotlib, numpy, opencv-python
Required-by:
```

**full tested code**
```
!wget -c 'https://i.ytimg.com/vi/vEYsdh6uiS4/maxresdefault.jpg'
pip install -U pyimkernel matplotlib
pip show pyimkernel
from pyimkernel import ApplyKernels
import cv2
import matplotlib.pyplot as plt
img = plt.imread("maxresdefault.jpg")
imkernel = ApplyKernels(random_seed = 0)
fig = plt.figure(figsize = (22, 22) )

plt.subplot(1, 3, 1)
plt.title("original")
plt.imshow(img)

sharpen3 = imkernel.apply_filter_on_color_img(img, kernel_name = 'sharpen', kernel_size = (3, 3) )
plt.imsave('sharpen3.png', sharpen3)

plt.subplot(1, 3, 2)
plt.title("sharpen3")
image0 = plt.imread('sharpen3.png')
plt.imshow(image0)

sharpen5 = imkernel.apply_filter_on_color_img(img, kernel_name = 'sharpen', kernel_size = (5, 5) )
plt.imsave('sharpen5.png', sharpen5)

plt.subplot(1, 3, 3)
plt.title("sharpen5")
image1 = plt.imread('sharpen5.png')
plt.imshow(image1)
```

**result**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/9f0cb1e7-930e-4b4f-9812-59193ce69f2c)

could you test my code on your machine ?

and also, if you want to share your code above, i'll test it on my machine too

including the source image file

**think, we have different point of view in this case :** 
**on my first post the same kernel name with the different kernel size** 
kernel name = sharpen with size 3x3
have so different result with 
kernel name = sharpen with size 5x5

**while your test is the same kernel size with different kernel name** 
kernel name = sharpen with size 3x3
with 
kernel name = unsharp mask with size 3x3

best regards

**Comment by amirho3einsedaghati** [comment]
In my previous comment, what I meant to say is that the issue is not related to the way the package is implemented, but rather to the values of the kernel itself. When the same kernel value is passed to cv2.filter2D or used with the ApplyKernel class, it will produce the same result. the following code proves the talk.

<pre>
import numpy as np
import matplotlib.pyplot as plt
import cv2
from pyimkernel import ApplyKernels
import os 
!wget -c https://i.postimg.cc/Jhfq3dv8/ice-age.jpg

image1 = cv2.imread(
    os.path.join('Images', 'ice-age.jpeg')
)

imkernel = ApplyKernels(random_seed=0)
plt.figure(figsize=(10, 10))

# 5x5 Sharpen Kernel
kernel_val = np.array([[-1, -1, -1, -1, -1],
                       [-1,  2,  2,  2, -1],
                       [-1,  2,  16, 2, -1],
                       [-1,  2,  2,  2, -1],
                       [-1, -1, -1, -1, -1]])

plt.subplot(1, 2, 1)
filtered_image = cv2.filter2D(image1, -1, kernel_val)
plt.imshow(cv2.cvtColor(filtered_image, cv2.COLOR_BGR2RGB))
plt.title('the result of the cv2.filter2D method')
plt.tight_layout()


plt.subplot(1, 2, 2)
plt.imshow(
 cv2.cvtColor(
    imkernel.apply_filter_on_color_img(
        image1,
        kernel_name='custom',
        kernel_value=kernel_val,
    ),
    cv2.COLOR_BGR2RGB
))
plt.title('the result of the imkernel.apply_filter_on_color_img method')
plt.tight_layout()
</pre>

![res1](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/79d98a33-d382-4d9d-82c9-5fbdf92ede1e)


and After running the following code, I found that there are several faults in some kernel values. and then explored some other kernel values to fix this issue.

<pre>
plt.figure(figsize=(20, 20))
plt.subplot(8, 7, 1)
plt.imshow(cv2.cvtColor(image1, cv2.COLOR_BGR2RGB))
plt.title('Orginal', size=15)
plt.axis('off')
plt.tight_layout()

kernel_names = ['guassian blur', 'guassian blur', 'bottom sobel', 'bottom sobel', 'left sobel', 'left sobel',
                'right sobel', 'right sobel', 'top sobel', 'top sobel', 'emboss', 'emboss', 'identity', 'identity',
                'outline', 'outline', 'sharpen', 'sharpen', 'vertical edge', 'vertical edge', 'horizontal edge',
                'horizontal edge', 'box blur', 'box blur', 'laplacian', 'laplacian', 'prewitt horizontal edge',
                'prewitt horizontal edge', 'prewitt vertical edge', 'prewitt vertical edge', 'high-pass filter',
                'high-pass filter', 'unsharp masking', 'unsharp masking', 'dilation', 'dilation', 'soften', 'soften', 
                'scharr horizontal edge', 'scharr horizontal edge', 'scharr vertical edge', 'scharr vertical edge',
                'motion blur', 'motion blur', 'robert horizontal edge', 'robert horizontal edge', 'robert vertical edge',
                'robert vertical edge', 'ridge detection1',  'ridge detection1', 'ridge detection2', 'ridge detection2']

kernels_sizes = [(3, 3), (5, 5)] * 26
kernels = list(zip(kernel_names, kernels_sizes))

for i in range(2, len(kernels) + 2):
    plt.subplot(8, 7, i)
    plt.title(f'{kernels[i-2][1][0]}x{kernels[i-2][1][1]} {kernels[i-2][0]}', size=15)
    plt.tight_layout()
    plt.axis('off')
    plt.imshow(
     cv2.cvtColor(
        imkernel.apply_filter_on_color_img(
            image1,
            kernel_name=kernels[i-2][0],
            kernel_size=kernels[i-2][1],
        ),
        cv2.COLOR_BGR2RGB
    ))
</pre>

the result of your image
![res2](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/521c64e6-ead4-4bfb-8386-fba120e0180a)

the result of my image
![res3](https://github.com/amirho3einsedaghati/pyimkernel/assets/59535996/e1787571-d630-40e2-8c3e-9fa23e101b20)

As you can see, there are evident faults in the values of the 5x5 outline, 5x5 sharpen, 5x5 ridge detection1, and 5x5 ridge detection2 kernels. In the next version, I will replace these kernels with the correct ones.

As you may already know, dilation kernels expand the bright regions or foreground in an image, which can make color images appear closer to white. However, I have developed a new version that performs this operation more effectively than the previous one.

Best Regards
