### ISSUE TITLE
filter effect image 

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#6]
nice to have filter effect image :
**e.g.**
**filters :**
contrast
grayscale
hue_rotate
saturate
sepia

**blend :**
color
color_burn
color_dodge
darken
difference
exclusion
hard_light
hue
lighten
multiply
normal
overlay
screen
soft_light

**ref**
https://github.com/mgineer85/pilgram2/tree/main/pilgram2/css
https://github.com/mgineer85/pilgram2/tree/main/pilgram2/css/blending

seems, pilgram2 use the matrix to apply the filter effect image

best regards

**Comment by amirho3einsedaghati** [comment]
Sounds like an interesting idea. Thank you for sharing it. I'll add this feature in the future version.

Best Regards @sugizo

**Comment by sugizo** [comment]
not sure, just a suggestion and want to discuss first, 
because 
matrix on color (rgba (red green blue alpha) ) 
is same like 
matrix on kernel image 
or not

if it same, then it can be nice to have feature 

if not, then, left it as is

**Comment by amirho3einsedaghati** [comment]
I've reviewed the Python files listed in the forwarded links. It seems like he manipulates the pixels of the input PIL image using mathematical formulas instead of using matrix-shaped kernels such as 3x3 or 5x5.

In fact, I can add this feature to the Pyimkernel package by defining a separate class. In this scenario, there wouldn't be a traditional kernel; rather, it would involve various manipulation techniques.
