### ISSUE TITLE
The shape of `source_im` is not the same as `backdrop_im`. 	    source_im : (225, 225, 3) and backdrop_im : (100, 100, 3)

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#9]
**code**
```
image0 = cv2.imread("ice_age.jpg")
image1 = cv2.imread("unsharp_masking_5.png")
image2 = cv2.imread("sepia.png")

hard_light = manipulation.hard_light(
    Image.fromarray(
        cv2.cvtColor(
            image1, cv2.COLOR_BGR2RGB
        ) ),
    Image.fromarray(
        cv2.cvtColor(
        image2, cv2.COLOR_BGR2RGB
    ) ),
)

hard_light.save('hard_light.png', 'png', quality = 100)

fig = plt.figure(figsize = (20, 20) )

plt.subplot(1, 3, 1)
plt.title("image1")
plt.imshow(cv2.cvtColor(image1, cv2.COLOR_BGR2RGB) )

plt.subplot(1, 3, 2)
plt.title("image2")
plt.imshow(cv2.cvtColor(image2, cv2.COLOR_BGR2RGB) )

plt.subplot(1, 3, 3)
plt.title("hard_light")
image3 = plt.imread('hard_light.png')
plt.imshow(image3)
```

**result**
```
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pyimkernel/main.py](https://localhost:8080/#) in __blending_techniques(self, func, backdrop_im, source_im)
    918             try:
--> 919                 filtered_image =  func(backdrop_im, source_im)
    920 

5 frames
ValueError: operands could not be broadcast together with shapes (225,225,3) (100,100,3) (100,100,3) 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pyimkernel/main.py](https://localhost:8080/#) in __blending_techniques(self, func, backdrop_im, source_im)
    920 
    921             except ValueError:
--> 922                 raise ValueError(f"The shape of `source_im` is not the same as `backdrop_im`.\n\t    source_im : {np.asarray(source_im).shape} and backdrop_im : {np.asarray(backdrop_im).shape}")
    923 
    924             else:

ValueError: The shape of `source_im` is not the same as `backdrop_im`.
	    source_im : (225, 225, 3) and backdrop_im : (100, 100, 3)
```

best regards

**Comment by amirho3einsedaghati** [comment]
When using blending techniques such as 'hard_light' and 'soft_light', it is important to ensure that the shape of the source image is the same as the backdrop image. If the shapes do not match, the Pyimkernel package will generate a 'ValueError' with a message like this:

<pre>ValueError: The shape of the source image is not the same as the backdrop image.
 Source image: (225, 225, 3) and backdrop image: (100, 100, 3).</pre>

To fix this issue, you need to resize the second source image to match the dimensions of the backdrop image. This step is necessary due to the functionality implemented in the 'hard_light.py' and 'soft_light.py' files of the Pilgram2 package.

So, you can fix it, by changing the hard_light technique like this :

<pre>
hard_light = manipulation.hard_light(
    Image.fromarray(
        cv2.cvtColor(
            image1, cv2.COLOR_BGR2RGB
        ) ),
    Image.fromarray(
        cv2.cvtColor(
            cv2.resize(
                image2,
                image1.shape[:2]
            ),
        cv2.COLOR_BGR2RGB
    ) ),
)
</pre>

Could it be helpful?

**Comment by sugizo** [comment]
**analysis**
the problem occured, 
when source size < backdrop size
but
when source size > backdrop size
it work

think your code above still need to check the size that meet my analysis above

**proven**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/5db19fc3-d755-4e4c-a4a1-4a503da679ba)

best regards

**Comment by amirho3einsedaghati** [comment]
Could you please provide the complete code that supports your analysis above? I have concerns about the accuracy of your analysis due to the functionality implemented in the 'hard_light.py' and 'soft_light.py' files of the Pilgram2 package.

Using the Pilgram2 package restricts me, preventing me from implementing and testing edge cases related to the package. I rely on this package to manipulate pixels using equivalent and blending techniques.

**Comment by sugizo** [comment]
**code**
```
!curl -LC - https://i.postimg.cc/Jhfq3dv8/ice-age.jpg -o ice_age.jpg

from pyimkernel import ApplyKernels, ManipulatePixels
from PIL import Image
import matplotlib.pyplot as plt

imkernel = ApplyKernels(random_seed = 0)
kernel_size_5 = (5, 5)
resize_value_custom = (100, 100)

resize_value = resize_value_custom

image = plt.imread("ice_age.jpg")

unsharp_masking_5 = imkernel.apply_filter_on_color_img(image, kernel_name = 'unsharp masking', kernel_size = kernel_size_5, with_resize = True, dsize = resize_value)

plt.imsave('unsharp_masking_5.png', unsharp_masking_5)

sepia = manipulation.sepia(Image.fromarray(image) )

sepia.save('sepia.png', 'png', quality = 100)

image0 = Image.open("ice_age.jpg")
image1 = Image.open("unsharp_masking_5.png")
image2 = Image.open("sepia.png")

soft_light = manipulation.soft_light(image0, image1)

soft_light.save('soft_light.png', 'png', quality = 100)

fig = plt.figure(figsize = (22, 22) )

plt.subplot(1, 3, 1)
plt.title("image0")
plt.imshow(image0)

plt.subplot(1, 3, 2)
plt.title("image1")
plt.imshow(image1)

plt.subplot(1, 3, 3)
plt.title("soft_light")
image3 = plt.imread('soft_light.png')
plt.imshow(image3)
```

`resize_value_custom = (100, 100)`
make it smaller than original size, 

then when it applied to hard_light or soft_light 
that 
source size > backdrop size
it work
as proven on my previous commented above

**Comment by amirho3einsedaghati** [comment]
Your provided code and analysis didn't work on my machine and Google Colab account because the shape of source_image doesn't match the dimensions of the backdrop image. 

**When the shape of source_image is the same as backdrop_image, the 'hard_light' and 'soft_light' techniques work correctly.**

here's your code and the result on my machine, just I added a print statement to see the shape of arrays

<pre>
!curl -LC - https://i.postimg.cc/Jhfq3dv8/ice-age.jpg -o ice_age.jpg

from pyimkernel import ApplyKernels, ManipulatePixels
from PIL import Image
import matplotlib.pyplot as plt

imkernel = ApplyKernels(random_seed = 0)
kernel_size_5 = (5, 5)
resize_value_custom = (100, 100)

resize_value = resize_value_custom

image = plt.imread("ice_age.jpg")

unsharp_masking_5 = imkernel.apply_filter_on_color_img(image, kernel_name = 'unsharp masking', kernel_size = kernel_size_5, with_resize = True, dsize = resize_value)

plt.imsave('unsharp_masking_5.png', unsharp_masking_5)

sepia = manipulation.sepia(Image.fromarray(image) )

sepia.save('sepia.png', 'png', quality = 100)

image0 = Image.open("ice_age.jpg")
image1 = Image.open("unsharp_masking_5.png")
image2 = Image.open("sepia.png")

# new line
print(f'shape image0 : {np.asarray(image0).shape}\nshape image1 : {np.asarray(image1).shape}\nshape image2 : {np.asarray(image2).shape}')

soft_light = manipulation.soft_light(image0, image1)
soft_light

soft_light.save('soft_light.png', 'png', quality = 100)

fig = plt.figure(figsize = (22, 22) )

plt.subplot(1, 3, 1)
plt.title("image0")
plt.imshow(image0)

plt.subplot(1, 3, 2)
plt.title("image1")
plt.imshow(image1)

plt.subplot(1, 3, 3)
plt.title("soft_light")
image3 = plt.imread('soft_light.png')
plt.imshow(image3)
</pre>

<b>Result</b>
<pre>
shape image0 : (225, 225, 3)
shape image1 : (100, 100, 4)
shape image2 : (225, 225, 3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/Projects/pyimkernel/pyimkernel/main.py:919, in ManipulatePixels.__blending_techniques(self, func, backdrop_im, source_im)
    918 try:
--> 919     filtered_image =  func(backdrop_im, source_im)
    921 except ValueError:

File ~/anaconda3/lib/python3.10/site-packages/pilgram2/css/blending/soft_light.py:95, in soft_light(im1, im2)
     68 """Darkens or lightens the colors, depending on the source color value.
     69 
     70 The soft light formula is defined as:
   (...)
     92     The output image.
     93 """
---> 95 return alpha_blend(im1, im2, _soft_light)

File ~/anaconda3/lib/python3.10/site-packages/pilgram2/css/blending/alpha.py:97, in alpha_blend(im1, im2, blending)
     96 im2, a2 = split_alpha(im2)
---> 97 im_blended = blending(im1, im2)
     99 if a1 is not None and a2 is not None:

File ~/anaconda3/lib/python3.10/site-packages/pilgram2/css/blending/soft_light.py:57, in _soft_light(im1, im2)
     56 cb_x_1_cb = util.apply_lut(im1, LUT_cb_x_1_cb)
---> 57 c1 = util.subtract(im1, ImageChops.multiply(_1_2_x_cs, cb_x_1_cb))
     59 _2_x_cs_1 = util.apply_lut(im2, LUT_2_x_cs_1)

File ~/anaconda3/lib/python3.10/site-packages/pilgram2/util/subtract.py:34, in subtract(im1, im2)
     33 im2 = np.asarray(im2)
---> 34 im = im1 - im2
     35 im = im.clip(0, 255).astype(np.uint8)

ValueError: operands could not be broadcast together with shapes (225,225,3) (100,100,3) 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[87], line 29
     25 image2 = Image.open("sepia.png")
     27 print(f'shape image0 : {np.asarray(image0).shape}\nshape image1 : {np.asarray(image1).shape}\nshape image2 : {np.asarray(image2).shape}')
---> 29 soft_light = manipulation.soft_light(image0, image1)
     30 soft_light
     32 soft_light.save('soft_light.png', 'png', quality = 100)

File ~/Projects/pyimkernel/pyimkernel/main.py:1307, in ManipulatePixels.soft_light(self, backdrop_im, source_im)
   1275 def soft_light(self, backdrop_im, source_im):
   1276     """Darkens or lightens the colors, depending on the source color value.
   1277 
   1278     The soft light formula is defined as:
   (...)
   1305         a PIL Image
   1306     """
-> 1307     return self.__blending_techniques(soft_light, backdrop_im, source_im)

File ~/Projects/pyimkernel/pyimkernel/main.py:922, in ManipulatePixels.__blending_techniques(self, func, backdrop_im, source_im)
    919     filtered_image =  func(backdrop_im, source_im)
    921 except ValueError:
--> 922     raise ValueError(f"The shape of `source_im` is not the same as `backdrop_im`.\n\t    source_im : {np.asarray(source_im).shape} and backdrop_im : {np.asarray(backdrop_im).shape}")
    924 else:
    925     return filtered_image

ValueError: The shape of `source_im` is not the same as `backdrop_im`.
	    source_im : (100, 100, 4) and backdrop_im : (225, 225, 3)
</pre>
